### ISSUE TITLE
Conversión de archivos .off a .stl

### ISSUE THREAD

**Issue by MarlonLLaguento** [MarlonLLaguento/TF-Machine-Learning-Humbser-Rommer-Diego-Marlon#2]

**Comment by MarlonLLaguento** [comment]
Esta parte es fundamental para tener poder entrenar la GAN.

**Comment by diegohumbser** [comment]
La transformación de archivos .off a .stl marca un hito esencial en la preparación de datos, allanando el camino para entrenar la GAN con modelos tridimensionales detallados y optimizados.

**Comment by AlcidesChewe** [comment]
completo
