### ISSUE TITLE
De archivo .stl a .binvox

### ISSUE THREAD

**Issue by MarlonLLaguento** [MarlonLLaguento/TF-Machine-Learning-Humbser-Rommer-Diego-Marlon#3]

**Comment by MarlonLLaguento** [comment]
Se intentó crear una función que haga la conversión de stl a voxel para poder trabajar de de una mejor manera con la GAN.

**Comment by AlcidesChewe** [comment]
Prueba con éxito, funciona correctamente

**Comment by diegohumbser** [comment]
La implementación de la función de conversión de .stl a .binvox es clave en la optimización de datos voxelizados, potenciando la capacidad predictiva y creativa de la GAN en tres dimensiones.
