### ISSUE TITLE
Primera versión de la GAN

### ISSUE THREAD

**Issue by MarlonLLaguento** [MarlonLLaguento/TF-Machine-Learning-Humbser-Rommer-Diego-Marlon#4]

**Comment by MarlonLLaguento** [comment]
Se creo un generador y discriminador que acepten archivos stl.

**Comment by AlcidesChewe** [comment]
se verifico la implementación, puede que suelte errores en la resolucion

**Comment by diegohumbser** [comment]
La creación del generador y discriminador para archivos .stl marca el inicio de la materialización digital de modelos tridimensionales.
